### ISSUE TITLE
So what about unity8.org ?

### ISSUE THREAD

**Issue by nazarimilad** [ubports/unity8#1]
I'm confused about which is going to be the official Unity 8 fork. This one or the one linked on http://unity8.org/ ?

**Comment by KoczurekK** [comment]
Hard to say. unity8.org clearly gathered more attention, but they only want to keep unity8, not whole ecosystem. I personally hope that ubports will leave unity8 development to unity8.org and work on OS / core apps themselves. IMHO it's most logical approach.

**Comment by nazarimilad** [comment]
That's a good and logical approach, indeed. There's already enough fragmentation.

**Comment by KoczurekK** [comment]
Yep, we could not only avoid fragmentation but also divide work in a way that lets everyone work relatively fast. But it all depends on what people from UBports decide, they'll have a conference at 18:00 UTC.

**Comment by Rodney78** [comment]
Hi all,

Per the last news, unity8.org (or the name that will be kept http://www.strawpoll.me/12696619/r) will focus on the development of Unity 8 for the desktop, and may use Wayland (as the team is not very large). 

I hope UBports will contribute to the mobile and convergence part!

**Comment by Leppan** [comment]
This should be closed.
Yunit do the desktop, UBPorts do mobile. Anything else goes in the Yunit part of the Forums.

**Comment by UniversalSuperBox** [comment]
Agreed. This repository is mostly a placeholder at this point.
