### ISSUE TITLE
Localization/translations from Yunit project

### ISSUE THREAD

**Issue by Aury88** [ubports/unity8#10]
Yunit project has done some unity8 interface localization/translation (149 languages in total, catalan french and italian are "ready for use" with 100% of the 3272 string translated, and portuguese need only 7 string translations) could it be usefull for ubports's unity8? 
they are in transifex but  John Salatas can export them in .po format or add me, or someone of you with a transifex account, as admin

### Update:

See https://github.com/ubports/unity8/issues/10#issuecomment-361513087  for zip containing translations

**Comment by Flohack74** [comment]
Ok nice, please prepare them in po format. For which subproject they are exactly?

**Comment by Aury88** [comment]
Hi @Flohack74 ! the subprojects are: account-plugins, address-book-service, click, content-hub, gnome-control-center-signon, gsettings-ubuntu-touch-schemas, hud, indicator-bluetooth, indicator-datetime, indicator-display, indicator-keyboard, indicator-location, indicator-messages, indicator-network, indicator-power, indicator-printers, indicator-session, indicator-sound, indicator-sync, indicator-transfer, indicator-transfer-buteo, libertine, libertine-scope, libusermetrics, location-service, oxide-qt, telephony-service, trust-store, ubuntu-download-manager, ubuntu-geoip, ubuntu-keyboard, ubuntu-settings-components, ubuntu-system-settings, ubuntu-system-settings-online-accounts, ubuntu-terminal-app, ubuntu-ui-extras, ubuntu-ui-toolkit, unity-control-center, unity-scope-mediascanner, unity-scope-shell, url-dispatcher, webbrowser-app, yunit
43 sub-projects in total

**Comment by Aury88** [comment]
ok @Flohack74, [here](https://github.com/ubports/unity8/issues/10#issuecomment-361513087) the file containing all subprojects with their  po files.

**Comment by Flohack74** [comment]
Oh Jesus its a LOT! Thx ;)

**Comment by Aury88** [comment]
you are welcome! let me know when you have what you need so I can remove  the PO files from dropbox ;-)
good luck with those translation, I hope they are useful

**Comment by dpniel** [comment]
[PO files.zip](https://github.com/ubports/unity8/files/1676832/PO.files.zip)

There you go @Aury88 i've attached the translations as a zip so we don't lose them and you can remove them from dropbox whenever you feel like it :-)

**Comment by Aury88** [comment]
Thank you @dpniel.... I tried myself to attach a zip here but I had an error, so I used dropbox. thank you very much!
