### ISSUE TITLE
The Drawer's sorting takes up too much space on mobile

### ISSUE THREAD

**Issue by UniversalSuperBox** [ubports/unity8#108]
The current default sort on the Drawer is "A-Z", which separates apps by the first letter in their name. This causes a couple of problems:

1. There are many categories with only one app, so we're using a lot of vertical space
1. In non-english languages, the first localized character of the app name is used. This causes even more groups to be created (one for localized names, another for non-localized English names). Languages with many letters weep.

Our current idea to solve this problem is to display all apps, sorted alphabetically, in a single group.

Here is the current design (on the Nexus 7):

![Nexus 7 Drawer](https://user-images.githubusercontent.com/21966173/54564579-1d7c7e00-499a-11e9-903f-8055b610dc71.png)

**Comment by mariogrip** [comment]
Fixed by: https://github.com/ubports/unity8/pull/120
