### ISSUE TITLE
Let Lockscreen to Rotate to the Current Device Orientation

### ISSUE THREAD

**Issue by cibersheep** [ubports/unity8#117]
1. Use the device with any orientation
2. Lock the screen
3. Unlock it

- Behaviour: screen rotates to primal orientation
- Expected: lockscreen to stay oriented to the device's current orientation

**Comment by mateosalta** [comment]
https://github.com/ubports/unity8/pull/273

**Comment by mateosalta** [comment]
This is also a usage issue for mounted devices, or usage with stands/cords - often times the hardware is dictating a better orientation, we need to adapt. 
- phone in landscape for navigation in car
- tablet upside down for charging stand (nexus 7)
- tablet upside down for case and cords (bq M10)
- phone with kickstand for bedside clock/alarm
- holding the phone while plugged into a external battery, extremely friendly to hold with cord on top

**Comment by cibersheep** [comment]
Oh, I forgot I [started](https://github.com/ubports/unity8/pull/315) to work into this and need to finish a little thing

**Comment by cibersheep** [comment]
I close this as is addressed here: https://github.com/ubports/unity8/issues/419
