### ISSUE TITLE
Black windows surfaces

### ISSUE THREAD

**Issue by fredldotme** [ubports/unity8#119]
With Unity8 on the Edge rootfs, after some time (around 2-3 days runtime), window surfaces only contain black color.
Touch-input seems to be passed through correctly.

Log of QQC2 Gallery application startup in such a scenario: https://paste.ubuntu.com/p/7dsyJFhMVd/

After Unity8 runs into such a situation only a reboot/restart of the shell can fix it until it occurs the next time.

**Comment by kugiigi** [comment]
Same issue on Nexus 5. Seems to happen when the system runs out of memory? which actually happens more often than the stable channel.

**Comment by NeoTheThird** [comment]
Is this still an issue? Might have been fixed along with #147?

**Comment by fredldotme** [comment]
Haven't noticed the issue again. Closing.
