### ISSUE TITLE
Re-start AyatanaIndicators discussion

### ISSUE THREAD

**Issue by NeoTheThird** [ubports/unity8#12]
[Ayatana](https://github.com/AyatanaIndicators) is a project that aims to make the same Indicators work across different desktop environments.

**Comment by Aury88** [comment]
Also some of the PO file in #10 can be partially used here (WARNING! they are not identical).

**Comment by dobey** [comment]
To follow along with my comments on other indicators design related issues, I don't think this is a particularly good idea. Having something this visible in the system, used by multiple environments, only serves to create issues, and some of those are unfixable. The indicators are already overly complex, with only having to deal with unity7 and unity8 simultaneously. Making them more generic will either only increase complexity, or force all environments to compromise and create something very basic that can meet the needs of all systems without special casing things.

As the goals of ubports/unity8 and other environments are quite different, I think rather instead, we should look to redesign the "indicators" interface entirely, and get rid of the existing indicators code (much of which is quite legacy and overly complicated). There are pieces from some indicators which will need to be re-used of course (Connectivity API is provided by indicator-network currently), but the majority of the code can be thrown out and replaced with something simpler and easier to maintain, I think.

**Comment by MohsenNz** [comment]
what is indicator ?

**Comment by cibersheep** [comment]
@MohsenNz the top-right area showing quick access information: notifications, connectivity, sound, system, etc:

![imatge](https://user-images.githubusercontent.com/6640041/58953218-19d8e600-8796-11e9-931b-3e705b0be2f9.png)

**Comment by MohsenNz** [comment]
> @MohsenNz the top-right area showing quick access information: notifications, connectivity, sound, system, etc:
> 
> ![imatge](https://user-images.githubusercontent.com/6640041/58953218-19d8e600-8796-11e9-931b-3e705b0be2f9.png)

oh ty.

**Comment by MohsenNz** [comment]
oh. Ty.

**Comment by lestcape** [comment]
Probably an useful read here: https://github.com/linuxmint/libappindicator/issues/1

**Comment by UniversalSuperBox** [comment]
The discussion has been sufficiently restarted. Support for the Ayatana forks of the ubuntuappindicators is added in https://github.com/ubports/unity8/pull/326
