### ISSUE TITLE
Behavior when tapping the background in the application spread

### ISSUE THREAD

**Issue by NeoTheThird** [ubports/unity8#121]
[In the past](https://bugs.launchpad.net/ubuntu/+source/unity8/+bug/1368261), this rationale was laid out for the current behavior of tapping the background in the application spread:

> When performing a long right edge swipe user enters application spread. If user end up there accidentally usually next thing he would like to do is to cancel the action to go back where he came from. Currently there is no way to cancel the spread. You can of course select the application from the stack that you came from but a dedicated cancel action would be nice.
>Desired solution:
>Tapping the spread background should cancel the spread and return to the application that was open when right edge gesture was started.

When this was implemented, we still had unity8-dash as the de-facto home-screen that users could always tap if they wanted to exit an application but not close it. Since we don't have that any more (and a long swipe from the left opens the drawer), there's no way to get to the desktop in staged mode. Could it make sense to change the behavior when tapping the background in the application spread to take you to the desktop rather than the last open application? Discuss!

**Comment by dobey** [comment]
What rationale is there for this? If nothing is broken with the current behavior as it was designed, then there's no need to change anything. If you want to go to the app drawer, then long swipe from left. Changing this to do as you suggest would make the behavior incredibly broken for anyone that accidentally opens the app spread and taps on the background to dismiss it, as all their apps would be hidden.

**Comment by cibersheep** [comment]
In cases like this, I like to see how Unity 7 behaves as is our grandpa.
Opening the «spread» (alt + tab) shows the [Desktop App] + [Opened apps]. Clicking outside of the spread cancels it (also esc). Probably is most obvious because the app underneath is the current app.

![imatge](https://user-images.githubusercontent.com/6640041/55789028-cf026100-5ab9-11e9-8f0c-7270ea348f2f.png)

Therefore, I suggest to go in the Unity way.

**Comment by NeoTheThird** [comment]
Not sure the unity 7 way translates too well, because the touch input is unique to unity 8. Of course, in windowed mode you would not want to minimize your applications when you accidentally click outside the spread. But in staged mode, that's a different story.

**Comment by UniversalSuperBox** [comment]
If I may interrupt, why don't we discuss this at https://forums.ubports.com/topic/2579/i-wanna-go-home? Long discussions are a little better over there.

**Comment by UniversalSuperBox** [comment]
Given the discussion continued on that forum thread, I believe this issue should be closed.
