### ISSUE TITLE
Possibly replace Oxide with QtWebEngine

### ISSUE THREAD

**Issue by NeoTheThird** [ubports/unity8#13]
The requirement for this is that it does not break any of the current APIs. This could be achieved by turning Oxide into a wrapper for QtWebEngine and QtWebView.

**Comment by jsalatas** [comment]
My initial idea to re-implement oxide-qt in a way that it is build as a wrapper around QtWebEngine and QtWebView while exposing the same API and thus be source compatible with the existing software. That would mean mainly 2 things
1) The existing unit tests in oxide-qt should continue to work without any (or at least minimal/straightforward) modifications to their code.
2) Eg for the desktop that would mean that we could compile the webbrowser app without any (or at least minimal/straightforward) modifications to its code.

I just extracted the current oxide's API documentation, which is available at https://jsalatas.ictpro.gr/oxide/ (maybe someone can upload it somewhere at ubports' web sites, just ask me to send these to you). 

As you can see it contains 3 major categories of classes/types that need to implemented

OxideQt Common C++ classes https://jsalatas.ictpro.gr/oxide/oxideqtcore-module.html
OxideQt QtQuick C++ classes https://jsalatas.ictpro.gr/oxide/oxideqtquick-module.html
OxideQt QML types https://jsalatas.ictpro.gr/oxide/com-canonical-oxide-qmlmodule.html
    
What I was planning (in yunit) to do is to go through all these classes and types and try to visualize these in UML-like (no need for strict diagrams) diagrams. And also create some kind of progress sheet about the progress and a roadmap on how to proceed. 

It seems to me that is a procedure that can be documented before hand, but it seems that it requires more than one developer to work with it. Maybe I could help with that but i cannot make any promises until at least we have a better understanding on what needs to be done (see diagrams, roadmap). 

It would be nice to hear additional thoughts about this. 

PS: When/if we start working can we have a wiki or something like that?

**Comment by jsalatas** [comment]
BTW: Forgot to mention previously but I'm under the impression that most of classes and types will end up just being wrappers (proxies) around corresponding QtWebEngines and QtWebViews classes and types, but we need to confirm that.

**Comment by dobey** [comment]
I guess this should be moved to oxide perhaps, or webbrowser-app (Ubuntu.Web is provided there and the officially supported API, the com.canonical.oxide API was not meant to be used directly), as unity8 itself has nothing to do with either of those.

I think the main issue here is going to be that QtWebEngine does not provide all the same API which oxide exposed, and so all of the API of oxide may not work with webengine.
