### ISSUE TITLE
[edge] Unity8's own focus is not respected

### ISSUE THREAD

**Issue by mariogrip** [ubports/unity8#130]
Unity8's own focus is not respected. 

A good example for this is have an app that shows the keyboard, then drag the top panel down, here it does not give the focus back to unity8 that results in the keyboard not getting dismissed.

**Comment by UniversalSuperBox** [comment]
It should be noted that this also causes the lock screen to not dismiss the keyboard, meaning someone can type in your apps even if the device is locked (assuming the keyboard was available when you locked the device)

**Comment by mariogrip** [comment]
Fixed by: https://github.com/ubports/unity8/pull/156
