### ISSUE TITLE
[edge] Some apps won't close

### ISSUE THREAD

**Issue by mariogrip** [ubports/unity8#131]
Some of the apps won't close

This seems to be non qt apps as far as i have debugged, it does receive the MirSurface::close call in qtmir but does nothing from there. It get removed from unity8's app list, but it's still running and can be seen when the spread is opening.

**Comment by UniversalSuperBox** [comment]
Can you explain how https://github.com/ubports/unity8/pull/160 and https://github.com/ubports/unity8/pull/159 relate to fixing this?

**Comment by prog66** [comment]
On hammerhead weather app won't close and crash ...

**Comment by UniversalSuperBox** [comment]
Fixed by https://github.com/ubports/qtmir/pull/26

**Comment by prog66** [comment]
Not fixed for me ....

**Comment by UniversalSuperBox** [comment]
The update won't be shipped until tomorrow
