### ISSUE TITLE
Unpin of shortcut while no apps running hides launcher

### ISSUE THREAD

**Issue by dobey** [ubports/unity8#133]
While the launcher is being shown as no apps are running, if one un-pins an app from the launcher, it will slide off screen. It should remain on-screen in this case.

**Comment by Danfro** [comment]
Fix confirmed on E5, RC. The launcher stays open.

**Comment by jonnius** [comment]
Fix confirmed on FP2, RC.

**Comment by cibersheep** [comment]
N5 RC, fix works

**Comment by j2g2rp** [comment]
Works fine on M10FHD and N5 on RC

**Comment by luksus42** [comment]
Fix confirmed on E4.5 on RC.
