### ISSUE TITLE
[Edge] Wrong scaling in convergence mode

### ISSUE THREAD

**Issue by krille-chan** [ubports/unity8#139]
When I have tested convergence mode with the Nexus 5 I saw that all apps have wrong scalings.

![screenshot20190517_113647210](https://user-images.githubusercontent.com/24619905/57919205-ae87ac80-7898-11e9-8635-c39c5e3f3736.png)

**Comment by UniversalSuperBox** [comment]
Duplicate of https://github.com/ubports/ubuntu-touch/issues/1095
