### ISSUE TITLE
Replace Scopes

### ISSUE THREAD

**Issue by NeoTheThird** [ubports/unity8#14]
Scopes are messy and don't converge. This is why the Canonical Unity8 team made the decision to remove unity-8-dash and the old scopes system, and the UBports team decided to stick with that and not bring unity8-dash back. The question now is, do we want to create a new system to provide functionality like scopes or widgets.

**Comment by ismaelbonato** [comment]
Maybe something like this

https://www.behance.net/gallery/29848255/Ubuntu-Touch-Vibrant-Venice

**Comment by NunuM** [comment]
I am interested in give my contribute in design and implement the scope feature.

**Comment by sverzegnassi** [comment]
@Flohack74 Is the 'help wanted' label valid? If so, I can de-assign myself and let someone else to take over the task ;)

**Comment by NeoTheThird** [comment]
No, please carry on :)

**Comment by Flohack74** [comment]
Sry did not see :)

**Comment by dobey** [comment]
Wouldn't the "quick fix" here to be just fix the dash app to only work in the stage perhaps? Those behance mock-ups would not work well for converged display either.

I would just get rid of the dash app and scopes for now, as the quickest solution. Yes some people might miss them, but they are confusing to develop, don't add significant benefit over building an app, and the system is a complex jumble of things that is difficult to maintain. Fixing the remaining issues in the app drawer and just dropping scopes is probably a better way forward.

**Comment by NeoTheThird** [comment]
@dobey Probably not clear enough in the description, but that's essentially the Idea. Removing the dash is an opportunity to get rid of a lot of legacy code and replace it with a clean solution that provides parts of the functionality eg the today scope had. @sverzegnassi has already something in the pipeline for that, so landing it is going to be quick and easy.

You are correct, scopes do not provide a lot of value, at least not the way they work at the moment. Multiple full-screen applications in a fixed rotation on your homescreen that are always open, that does not provide anything that could not be done just as easily (or even better) in a traditional applications. The development process is painful, so there are not a lot (if any) high-quality scopes that still work anyways, so we do not need to keep API compatibility. But a widget-like context-information-on-the-homescreen situation can be useful.

**Comment by dobey** [comment]
Widgets on the background opens up some security issues, depending on how it's done.

**Comment by NeoTheThird** [comment]
This would not be something that can be installed from the store, though. I don't see the security issue.

**Comment by dobey** [comment]
What's the point of having any widgets if you can't install your own?
