### ISSUE TITLE
[Edge] Wrong size of the Indicators Bar

### ISSUE THREAD

**Issue by cibersheep** [ubports/unity8#145]
Tested devices: E5 **2019-05-28**, **N5 2019-15/2**, **2019-05-28**
1) Unlock device
2) Place device on landscape
3) Pull indicators bar other than notifications

- Indicators are shifted (sometimes to the right, sometimes to the left).
- Shifting increases by rotating the device sometimes showing shifting also in portrait mode.
- If notification bar is pulled from notifications area (if not empty) looks centered

![imatge](https://user-images.githubusercontent.com/6640041/58499165-d5d75700-817f-11e9-8f5b-41f523af8bae.png)

**Comment by mariogrip** [comment]
Fixed by: https://github.com/ubports/unity8/pull/158

**Comment by Flohack74** [comment]
I still have this on my OPO on edge, from 2019-09-21

**Comment by Flohack74** [comment]
Ok maybe its different, I will make a new ticket...
