### ISSUE TITLE
[Edge] Can't Pull Indicators Bar from Left Side of the Bar

### ISSUE THREAD

**Issue by cibersheep** [ubports/unity8#146]
Related with #132?
1) Try to pull indicators bar from the left of the notifications area

- Expected: bar pulls down
- Behave: Bar doesn't respond

Tested on E5, N5

**Comment by UniversalSuperBox** [comment]
This is by design owing to the addition of the ApplicationMenu to the Panel.

https://imgur.com/McasJWs

**Comment by cibersheep** [comment]
Oh, I see
