### ISSUE TITLE
Resizing windows uses more RAM and eventually crash Unity 8

### ISSUE THREAD

**Issue by kugiigi** [ubports/unity8#147]
Channel: Edge
Device: Nexus 7 2013, Nexus 5

### Steps to reproduce
1. Switch to desktop mode.
2. Open an app
3. Resize the window repeatedly

Optional: Open Terminal, run `top` or `htop` and monitor the free memory.

### Expected Results
1. The window resizes smoothly and Unity 8 won't crash.

### Actual Results
Memory usage increases continuously until Unity 8 crash. Resizing is also not smooth and stutters.

**Comment by kugiigi** [comment]
Xmir (libertine apps) doesn't seem to have the same issue when resizing the window.

**Comment by UniversalSuperBox** [comment]
When resizing the window, the following appears in `logcat` on every frame (or so):

```
W/Adreno-EGL( 2838): <qeglDrvAPI_eglDestroyImageKHR:4773>: EGL_BAD_PARAMETER
E/libEGL  ( 2838): validate_display:261 error 3008 (EGL_BAD_DISPLAY)
```

Investigating further, I've found that this occurs when our `EGLImageKHR` representing the app's space to draw tries and fails to `eglDestroyImageKHR` itself at https://github.com/ubports/mir/blob/master/src/server/graphics/nested/buffer.cpp#L82.

The error `EGL_BAD_PARAMETER` is shown by `eglDestroyImageKHR` when the image is not correct with respect to the given display. However, in the implementation on-device, `eglGetDisplay` or `eglGetCurrentDisplay` will only ever return `1`. It doesn't seem like there's any way to mess up that call.

I wondered why we were passing `EGL_NO_CONTEXT` as the context for creating the image. When passing in our current EGL context, app windows appear as black screens and the keyboard overlay covers the entire screen with black. So... that's not it.
