### ISSUE TITLE
Create documentation for Unity8

### ISSUE THREAD

**Issue by NeoTheThird** [ubports/unity8#15]
Build docs, install docs, getting-started docs. Document all the things!

**Comment by ismaelbonato** [comment]
Is README included?

**Comment by MohsenNz** [comment]
hi. where is documentation?

**Comment by filman230** [comment]
@MohsenNz I know I'm here one year later, but in case someone wants to know: they use [doxygen](https://www.doxygen.nl/index.html) to generate the documentation from the source code. So to generate the doc with Lomiri (unity8), download the source code then:
- Create a folder named 'build' (the name is not really important, though)
- Inside the 'build' folder, run `cmake -DCMAKE_INSTALL_PREFIX:PATH=/usr -DCMAKE_INSTALL_LIBDIR="lib/" ..` in terminal
- Finally, run `make doc` (still inside 'build'). This will generate the documentation.
You can then access it inside the subfolder 'doc/unity' inside the folder 'build' (_not_ the 'doc' folder that is at the top of the code folder), by opening `index.html` with your browser.

To generate the doc, you will nedd the packages `doxygen` and `doxyqml`.
