### ISSUE TITLE
Unity 8 can not login

### ISSUE THREAD

**Issue by sangqle** [ubports/unity8#150]
After i install unity in my machine then i restart system but when i choose unity8 and typing my password to login into system but i can not do that and i received login screen again with input password box

**Comment by dobey** [comment]
Are you on 18.04? It is known you will need to log in twice for it to start currently.

**Comment by sangqle** [comment]
Yep i using 18.04. i even log in 5th but it not working then i have already uninstall unity8

**Comment by dobey** [comment]
Check the log of unity8 with `journalctl --user-unit unity8.service`

**Comment by sangqle** [comment]
Thanks @dobey i will try.

**Comment by AlanGriffiths** [comment]
Which DM are you using?

I've seen a [similar problem](https://github.com/MirServer/egmde-snap/issues/2) with egmde when using lightdm (but no problems with sddm).

Here are some other issues I collected there:

- https://github.com/ubports/unity8-desktop-install-tools/issues/22
- https://github.com/ubports/unity8-desktop-install-tools/issues/29
- https://github.com/ubports/unity8-desktop-install-tools/issues/30
- https://github.com/ubports/unity8-desktop-install-tools/issues/36

I don't see anything inspiring in the comments though.

**Comment by OMGdaDPS** [comment]
hello all! im experiencing this same issue. 
Like the OP stated, I have also relogged multiple times and tried rebooting multiple.
Ill check the logs and get back to you

**Comment by OMGdaDPS** [comment]
I'm going to try and replicate this issue on 4 different machines today, since I'm not doing anything else. I'll get back to you with the results. Anything super useful that I could provide?

**Comment by AlanGriffiths** [comment]
> I'm going to try and replicate this issue on 4 different machines today, since I'm not doing anything else. I'll get back to you with the results. Anything super useful that I could provide?

The DM used, and corresponding logs. As in https://github.com/MirServer/egmde-snap/issues/2

[edit]
There's a possible solution (needing a developer) noted there too.

**Comment by OMGdaDPS** [comment]
> > I'm going to try and replicate this issue on 4 different machines today, since I'm not doing anything else. I'll get back to you with the results. Anything super useful that I could provide?
> 
> The DM used, and corresponding logs. As in [MirServer/egmde-snap#2](https://github.com/MirServer/egmde-snap/issues/2)
> 
> [edit]
> There's a possible solution (needing a developer) noted there too.

I've been out for a few days, but I'm home now. Warming my rigs up now.

**Comment by profmonjl** [comment]
> Check the log of unity8 with `journalctl --user-unit unity8.service`

jl@ubuntu:~$ journalctl --user-unit unity8.service
-- Logs begin at Wed 2019-10-16 14:21:47 PDT, end at Wed 2019-10-16 15:36:58 PDT. --
Oct 16 15:32:44 ubuntu systemd[1337]: Starting Unity Shell v8...
Oct 16 15:32:44 ubuntu systemd[1337]: Started Unity Shell v8.
Oct 16 15:33:03 ubuntu systemd[1561]: Starting Unity Shell v8...
Oct 16 15:33:04 ubuntu unity8-session[1682]: [2019-10-16:15:33:04.130] qt.qpa.screen: QXcbConnection: Could not connect to display
Oct 16 15:33:04 ubuntu unity8-session[1682]: [2019-10-16:15:33:04.130] Could not connect to any X display.
Oct 16 15:33:04 ubuntu unity8-session[1682]: /usr/bin/unity8-session: line 76: [: !=: unary operator expected
Oct 16 15:33:04 ubuntu unity8-session[1682]: /usr/bin/unity8-session: line 80: kill: (1740) - No such process
Oct 16 15:33:04 ubuntu systemd[1561]: Started Unity Shell v8.
Oct 16 15:33:18 ubuntu systemd[1778]: Starting Unity Shell v8...
Oct 16 15:33:18 ubuntu unity8-session[1903]: [2019-10-16:15:33:18.363] qt.qpa.screen: QXcbConnection: Could not connect to display
Oct 16 15:33:18 ubuntu unity8-session[1903]: [2019-10-16:15:33:18.363] Could not connect to any X display.
Oct 16 15:33:18 ubuntu unity8-session[1903]: /usr/bin/unity8-session: line 76: [: !=: unary operator expected
Oct 16 15:33:18 ubuntu unity8-session[1903]: /usr/bin/unity8-session: line 80: kill: (1965) - No such process
Oct 16 15:33:18 ubuntu systemd[1778]: Started Unity Shell v8.

I am suing gmd to login.

**Comment by ezze** [comment]
Tried on Kubuntu 18.04 with sddm.

```
ezze@yellowberry:~$ journalctl --user-unit unity8.service
-- Logs begin at Fri 2019-01-11 12:21:03 MSK, end at Mon 2019-10-21 20:37:29 MSK. --
окт 21 20:34:38 yellowberry systemd[2231]: Starting Unity Shell v8...
окт 21 20:34:38 yellowberry unity8-session[15476]: [2019-10-21:20:34:38.503] qt.qpa.screen: QXcbConnection: Could not connect to display
окт 21 20:34:38 yellowberry unity8-session[15476]: [2019-10-21:20:34:38.503] Could not connect to any X display.
окт 21 20:34:38 yellowberry unity8-session[15476]: /usr/bin/unity8-session: line 76: [: !=: unary operator expected
окт 21 20:34:38 yellowberry unity8-session[15476]: /usr/bin/unity8-session: line 80: kill: (15488) - No such process
окт 21 20:34:38 yellowberry systemd[2231]: Started Unity Shell v8.
окт 21 20:35:15 yellowberry systemd[2231]: Starting Unity Shell v8...
окт 21 20:35:15 yellowberry unity8-session[16534]: [2019-10-21:20:35:15.251] qtmir.screens: ScreensModel::ScreensModel
окт 21 20:35:15 yellowberry unity8-session[16534]: [2019-10-21:20:35:15.251] QSocketNotifier: Can only be used with threads started with QThread
окт 21 20:35:15 yellowberry unity8-session[16534]: [2019-10-21 20:35:15.254087] mirserver: Starting
окт 21 20:35:15 yellowberry unity8-session[16534]: [2019-10-21 20:35:15.257235] <DEBUG> mirserver: Using logind for session management
окт 21 20:35:15 yellowberry unity8-session[16534]: [2019-10-21 20:35:15.257304] mircommon: Loading modules from: /usr/lib/x86_64-linux-gnu/mir/server-platform
окт 21 20:35:15 yellowberry unity8-session[16534]: [2019-10-21 20:35:15.257337] mircommon: Loading module: /usr/lib/x86_64-linux-gnu/mir/server-platform/graphics-mesa-kms.so.16
окт 21 20:35:15 yellowberry unity8-session[16534]: [2019-10-21 20:35:15.257358] mircommon: Loading module: /usr/lib/x86_64-linux-gnu/mir/server-platform/server-mesa-x11.so.16
окт 21 20:35:15 yellowberry unity8-session[16534]: [2019-10-21 20:35:15.257368] mircommon: Loading module: /usr/lib/x86_64-linux-gnu/mir/server-platform/input-evdev.so.7
окт 21 20:35:15 yellowberry unity8-session[16534]: [2019-10-21 20:35:15.259961] mesa-kms: EGL platform does not support EGL_KHR_platform_gbm extension
окт 21 20:35:15 yellowberry unity8-session[16534]: [2019-10-21 20:35:15.260966] mesa-kms: Device /dev/dri/card0 does not support KMS
окт 21 20:35:15 yellowberry unity8-session[16534]: [2019-10-21 20:35:15.261003] mirplatform: Found graphics driver: mir:mesa-kms (version 1.1.2) Support priority: 0
окт 21 20:35:15 yellowberry unity8-session[16534]: [2019-10-21 20:35:15.261020] mirplatform: Found graphics driver: mir:mesa-x11 (version 1.1.2) Support priority: 0
окт 21 20:35:15 yellowberry unity8-session[16534]: [2019-10-21:20:35:15.261] Exception while creating graphics platform
окт 21 20:35:15 yellowberry unity8-session[16534]: ERROR: /build/varlibjenkinsworkspaceubportsmirbionicmirgbpfdsc/src/platform/graphics/platform_probe.cpp(109): Throw in function std::shared_ptr<mir::SharedLibrary> mir::graphics::module_for_device(const std::vector<std::
окт 21 20:35:15 yellowberry unity8-session[16534]: Dynamic exception type: boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<std::runtime_error> >
окт 21 20:35:15 yellowberry unity8-session[16534]: std::exception::what: Failed to find platform for current system
окт 21 20:35:15 yellowberry unity8-session[16534]: /usr/bin/unity8-session: line 76: [: !=: unary operator expected
окт 21 20:35:15 yellowberry unity8-session[16534]: /usr/bin/unity8-session: line 80: kill: (16546) - No such process
окт 21 20:35:15 yellowberry systemd[2231]: Started Unity Shell v8.
```

**Comment by OMGdaDPS** [comment]
I know that this is a dumb question, but I check the logs of unity8 by opening a session that actually works and running that command, correct? Sorry for the late response. Been SUPER busy.

**Comment by ezze** [comment]
@OMGdaDPS, you run `journalctl` command from any working terminal session (for example, under GNOME or KDE, or even without any desktop environment). Due to you can't login with Unity8, I guess, you are unable to run the command there. :)

I tried the same on a fresh installation of Ubuntu 18.04 running in Virtual Box 5.2.32, and still no luck. There is some issue with display connection (like @profmonjl already mentioned):

```
окт 21 23:56:42 ubuntu-18 systemd[1417]: Starting Unity Shell v8...
окт 21 23:56:42 ubuntu-18 unity8-session[1535]: [2019-10-21:23:56:42.032] qt.qpa.screen: QXcbConnection: Could not connect to display
окт 21 23:56:42 ubuntu-18 unity8-session[1535]: [2019-10-21:23:56:42.032] Could not connect to any X display.
окт 21 23:56:42 ubuntu-18 unity8-session[1535]: /usr/bin/unity8-session: line 76: [: !=: unary operator expected
окт 21 23:56:42 ubuntu-18 unity8-session[1535]: /usr/bin/unity8-session: line 80: kill: (1547) - No such process
окт 21 23:56:42 ubuntu-18 systemd[1417]: Started Unity Shell v8.
```

**Comment by ezze** [comment]
Looking at issues listed by @AlanGriffiths above I got it working on the [third login attempt](https://github.com/ubports/unity8-desktop-install-tools/issues/29).

**Comment by MartijnVerkleij** [comment]
Hi there! I got it working by adding double quotes (`"`) around the command before the `!=` on line 76 of `/usr/bin/unity8-session`.

**Comment by AlanGriffiths** [comment]
> Hi there! I got it working by adding double quotes (`"`) around the command before the `!=` on line 76 of `/usr/bin/unity8-session`.

Hello @MartijnVerkleij that sounds like something you should create a PR for. I'm not sure which project `/usr/bin/unity8-session` comes from, but
```plain
dpkg -S /usr/bin/unity8-session
```
will tell you you the package that installed it (which ought to provide a clue).

**Comment by UniversalSuperBox** [comment]
I believe this issue was filed regarding a unity8 desktop installer. We are not currently able to offer support for this... We may release more proper desktop installers with our transition of Ubuntu Touch to Ubuntu 20.04, or another distribution may provide proper images with Lomiri.

Either way, I believe this issue should be closed since this revision of the project is essentially dropped. Lomiri will still come back to the desktop, but not using unity8-desktop-install-tools.

**Comment by AlanGriffiths** [comment]
@UniversalSuperBox you're probably right to close this, but the pedant in me wants to point out it wasn't about any installer.

It is about launching a user session from a greeter (presumably something puts a `.desktop` file in `/usr/share/xsessions`). As such it is a mess of interactions between projects that have likely all changed over time.
