### ISSUE TITLE
Indicators content sometimes has invalid position

### ISSUE THREAD

**Issue by mariogrip** [ubports/unity8#157]
Indicators content sometimes has invalid position, where the content is shifted to the left. (see screenshot)

This seems to happen when used for a while, maybe after rotation but not sure. Using it daily i see this happen from time to time.

![screenshot20190627_154319494](https://user-images.githubusercontent.com/1642635/60271606-f87d9c80-98f2-11e9-99cc-fa47780acc75.png)

**Comment by cibersheep** [comment]
Duplicate #145
:*

**Comment by mariogrip** [comment]
> Duplicate #145
> :*

Sorry about that! I did search for one, but i forgot to search in the unity8 repo :( I only searched in ubuntu touch repo, I'll search better next time :) will edit my pr to include that 

Duplicate of: https://github.com/ubports/unity8/issues/145
