### ISSUE TITLE
Look into HUD and Global Menues

### ISSUE THREAD

**Issue by NeoTheThird** [ubports/unity8#16]
The HUD is the greatest thing since sliced bread. If you disagree, you are wrong.

**Comment by GizmoChicken** [comment]
Given that Locally Integrated Menus ([LIM](http://www.webupd8.org/2014/02/ubuntu-1404-gets-locally-integrated.html)) are sort of related to Global Menus, would it be appropriate to add looking into LIM to this issue?  If not appropriate here, I'll open a new issue focusing on LIM.

**Comment by UniversalSuperBox** [comment]
The newest version of Unity8 shipping on Ubuntu Touch phones now supports the global menu and the locally-integrated menu. Additional support is needed from native Ubuntu Touch applications and from Libertine, but I believe this issue's requirements are satisfied.
