### ISSUE TITLE
Fullscreen apps are remembered, will not go back to not-fullscreen

### ISSUE THREAD

**Issue by NeoTheThird** [ubports/unity8#170]
The browser is showing some unexpected behavior on edge, it seems to be running in full-screen. This leads to the following issues:

- The indicator bar is not shown
- The browser can not be moved in a window in desktop mode
- The launcher and app drawer can not be opened in desktop mode
- The top bar shows up while dragging out the launcher and drawer and disappears again when the the drawer is fully extended, leading to weird shifting around
- Working with multiple windows is a pain in the ass
- Side stage sometimes works and sometimes doesn't
- Top bar disappears if browser is focused in side-stage and re-appears if focus is switched to the app in main stage

I don't see anything interesting going on in the logs for browser or unity8. Might be caused by ubports/unity8#144. Have not observed this behavior with other full-screen apps such as Pathwind.

**Comment by UniversalSuperBox** [comment]
It seems like this sort of problem affects any app which uses fullscreen, so I've moved it to unity8.

**Comment by UniversalSuperBox** [comment]
Fixed by https://github.com/ubports/unity8/pull/172
