### ISSUE TITLE
Better x11 support

### ISSUE THREAD

**Issue by mariogrip** [ubports/unity8#18]
With this we need to be able to have a "stand by" x11 socket that will spawn Xmir/Xwayland on event

We would also like to have *one* Xserver server since the applications expect to run on the same server. We would also need to create a x wm, without this unity8 will just group everything x11 into one "app".

This will also need to shut down after all sessions gone.

**Comment by NeoTheThird** [comment]
Probably intersting: https://community.ubuntu.com/t/supporting-x11-clients-on-mir-servers/4244

**Comment by AlanGriffiths** [comment]
X11 support is better handled upstream, in Mir:
https://community.ubuntu.com/t/supporting-x11-clients-on-mir-servers/4244/2

**Comment by MohsenNz** [comment]
hi . how can i help in this topic?
also unity 8 on my Ubuntu 18.04 not work and crash.

**Comment by AlanGriffiths** [comment]
> hi . how can i help in this topic?

The planned X11 support is mostly in Mir and working on it there is the best way to help.  There's only [one issue](https://github.com/MirServer/mir/issues/479) logged, but I'm confident that is only because people are not trying it.

If you want to help with that, you'll be welcome in the MirServer/mir project.

(I'm the Mir team lead, and don't know anything about the current problems Unity8 has on 18.04 except that they need fixing before integrating the X11 support here would be useful.)

**Comment by dobey** [comment]
@AlanGriffiths Is that comment about running Mir on top of X11? Or about Mir launching an Xwayland instance if it's not running and an X11 client tries to access the display socket?

For the latter, there's a lot more problems due to app authentication to be able to talk to Mir and such. I've so far been able to get Xwayland to apparently connect and run, but I've not been able to get any apps to connect to the `$DISPLAY` yet. But I think this is lower priority than a lot of other current issues with unity8.

**Comment by AlanGriffiths** [comment]
@dobey It's about Mir controlling an Xwayland process.

I've only used it with `mir_demo_server` and `egmde` and getting apps to connect works fine. Here's a simple working scenario:

```bash
sudo apt-add-repository ppa:mir-team/release
sudo apt install mir-test-tools mir-graphics-drivers-desktop xwayland xeyes
mir_demo_server --x11-display 3&
DISPLAY=:3 xeyes
```
(You can do that running Mir on an X11 supporting or from a VT.)

**Comment by AlanGriffiths** [comment]
If you think something isn't working there's https://github.com/MirServer/mir/issues

**Comment by dobey** [comment]
@AlanGriffiths  Yeah, we've had this conversation before. I'm not sure that the problem has anything to do with Mir, but is more related to the unity8 architecture (the authorizing clients in qtmir, and environment related things).

**Comment by MohsenNz** [comment]
@dobey now . should i join to mir project or should do other works?

**Comment by AlanGriffiths** [comment]
@dobey I think I understand a bit better than last time around. This sounds like QtMir's [SessionAuthorizer](https://github.com/ubports/qtmir/blob/master/src/platforms/mirserver/sessionauthorizer.cpp) rejecting Xwayland as a client.

@MohsenNz maybe this is a theory you could investigate? And fix?

**Comment by MohsenNz** [comment]
> @MohsenNz maybe this is a theory you could investigate? And fix?

What do you mean?

**Comment by AlanGriffiths** [comment]
> What do you mean?

The X11-via-Xwayland support in Mir works (for a generous value of "works") in Mir demo applications, and egmde.

Apparently it doesn't work in Unity8. From what Rodney says about the way it fails, that sounds like a problem in QtMir's SessionAuthorizer.

If you want to help with the X11 support specifically, that sounds like something you could investigate.

IIRC QtMir contains a small test shell you can experiment with, without the need to build the rest of the Unity8 stack. (I don't know if that shows this problem though.)

**Comment by dobey** [comment]
I think the Xwayland-on-Unity8 issues are probably not a good first thing to start with. There's a lot of code and issues in unity8 (not all of which are documented on github yet). Filing issues would be a good place to start, with helpful debugging info (ie, more than "everything crashes").

**Comment by mariogrip** [comment]
I have to agree with @dobey, and also note that the xwayland impl in mir is still highly experimental with lots of bad code. This part of the code needs to be somewhat usable without random crashes that happens sometimes with it. (https://github.com/MirServer/mir/tree/master/src/server/frontend_xwayland)

**Comment by AlanGriffiths** [comment]
I agree. The X11/Xwayland code isn't the highest priority for Unity8 or Mir.

But if someone wants to "help in this topic" there's useful things to do.

**Comment by MohsenNz** [comment]
one question. what is benefit of Mir? why canonical continue development of Mir?
we can use Wayland on embedded system as well , i think.

**Comment by AlanGriffiths** [comment]
> one question. what is benefit of Mir? why canonical continue development of Mir?
> we can use Wayland on embedded system as well , i think.

This issue "Better x11 support" (for Unity8) is the wrong place for that discussion. Head on over to https://discourse.ubuntu.com/c/mir

**Comment by AlanGriffiths** [comment]
> The X11/Xwayland code isn't the highest priority for Unity8 or Mir.

That situation has changed: [X11 support has finally got to the top of the Mir list](https://discourse.ubuntu.com/t/server-side-decorations-landed-for-xwayland/13678).

**Comment by UniversalSuperBox** [comment]
I believe this report no longer has the appropriate context to be useful, and it was never specific enough to ever be classified as "done."
