### ISSUE TITLE
Launcher not shown after Welcome screen

### ISSUE THREAD

**Issue by NeoTheThird** [ubports/unity8#198]
After the "Welcome to Ubuntu" screen, the launcher should be visible.

**Comment by dobey** [comment]
I presume this is on edge channel, and you do mean _launcher_ rather than _drawer_ right?

**Comment by NeoTheThird** [comment]
Yes. The drawer should be hidden, in my opinion.

**Comment by dobey** [comment]
OK. The launcher should be shown already when there are no open windows, but I think there are still some cases where that might be slightly buggy.

**Comment by NeoTheThird** [comment]
Iirc the launcher recieves a signal if the amount of open windows changes. and shows if there's none. But on the first boot, there has never been an open window, so it does not change. What i would imagine is for the launcher to come up after clicking the "Get Started" button.

Typing this i realize that this might clash with the tutorial, which includes a card to tell you how to open the launcher, so maybe this should only happen in windowed mode?

**Comment by UniversalSuperBox** [comment]
The Launcher normally doesn't hide in windowed mode, so no need there.

**Comment by NeoTheThird** [comment]
@UniversalSuperBox That's what i mean, it's not there after the first boot. Filed this issue after booting the pinebook, which defaults to windowed mode.

**Comment by UniversalSuperBox** [comment]
Oh, well that changes things

**Comment by UniversalSuperBox** [comment]
This has been fixed by https://github.com/ubports/unity8/pull/274
