### ISSUE TITLE
Indicator menue: Items got desynced from selection logic

### ISSUE THREAD

**Issue by Flohack74** [ubports/unity8#201]
I somehow managed to get selected indicator desynced with the white selection bar:
![grafik](https://user-images.githubusercontent.com/16186470/65986087-78337e00-e483-11e9-9412-127f00e9a841.png)
On the top you can see that Notifications is selected on the left, where the white bar is on the rightmost indicator. Also there is no content now.

**Comment by UniversalSuperBox** [comment]
Duplicate of https://github.com/ubports/unity8/issues/132 and https://github.com/ubports/unity8/issues/132

**Comment by Flohack74** [comment]
U sure its a duplicate of 2x the same ticket no? =)
