### ISSUE TITLE
Edge: OSK is unstable

### ISSUE THREAD

**Issue by lduboeuf** [ubports/unity8#214]
Got several bugs related with OSr but randomly:

Blank area: 
 sometimes keyboard is not visible, only we see the reserved area on the screen 

Keyboard is dismissed after each key: 
Occured mostly on messaging app ( don't remember elsewhere )
 
OSK does not appear at all on inputs ( Morph browser) -> first time today on Github. Can it be the chromium version ?

**Comment by UniversalSuperBox** [comment]
This doesn't seem like an appropriate place to file these issues, nor is it useful to file multiple problems in a single ticket. Could you split these out and file them on more appropriate repositories?

**Comment by lduboeuf** [comment]
ok will do, thought it was a Unity8 problem
