### ISSUE TITLE
Indicator can be horizontally scrolled

### ISSUE THREAD

**Issue by kugiigi** [ubports/unity8#219]
## Device
Nexus 5/ MX4
Edge

## Description
I noticed that the indicator can be swiped or scrolled horizontally which I don't remember happening before. This usually happens when you try to swipe down fast and the same time try to swipe sidewards. Just to be clear, this is when the indicator is now yet in the expanded state.

**Comment by lduboeuf** [comment]
is it an issue ? For me the indicator horizontal navigation always been there

**Comment by kugiigi** [comment]
This is what I'm talking about 😉
![screenshot20191031_121224451](https://user-images.githubusercontent.com/29456786/67926170-99d47200-fbb5-11e9-9821-f7eb1bb296d2.png)

**Comment by giiba** [comment]
This seems to be fixed as of dev 1315 on OPO. The indicators now nicely expand when touched and the odd behaviour is gone.

**Comment by UniversalSuperBox** [comment]
Excellent. Was probably fixed by https://github.com/ubports/unity8/pull/276.
