### ISSUE TITLE
[N5][Edge] Screen brightness can't be changed

### ISSUE THREAD

**Issue by cibersheep** [ubports/unity8#222]
Update: 2019-11-02/02
Device: Nexus 5

- Pull down indicators / go to Settings > Battery > Screen brightness
- Move slider to change brightness

Expected: Select from dim to bright screen brightness
Actual behaviour: Brightness level is fixed.

**Comment by Flohack74** [comment]
Thats probably a problem of the device port and as such not part of unity8. Also, edge channel breaks from time to time intentionally when devs are doing heavier lifting, I would not consider that bugs should be reported against edge at all ;)

**Comment by cibersheep** [comment]
So let's get rid of this in 3,
