### ISSUE TITLE
App spread closes when the first app in the list is closed

### ISSUE THREAD

**Issue by kugiigi** [ubports/unity8#225]
## Device
Nexus 5
Edge/Devel

## Steps to reproduce
1. Open at least 3 apps.
2. Open the app spread (long swipe from the right)
3. Close the right-most app in the spread (swipe up or down)
4. Close the left-most app in the spread.

## Expected Behavior
The right-most app is closed and removed from the spread.
The left-most app is closed and removed from the spread.
The app spread is still displayed and open after closing the apps.

## Actual Behavior
The right-most app is closed and removed from the spread.
The left-most app is closed and also closes the app spread and focuses on the next app in the spread from the left.

**Comment by ghost** [comment]
I can confirm this behavior.
- Oneplus One - dev
- BQ E5 - rc
- Oneplus 3T - edge
