### ISSUE TITLE
Application list not updated when installing via pkcon

### ISSUE THREAD

**Issue by mardy** [ubports/unity8#242]
Hi all!
  I've just flashed the devel channel, and it comes with the new luancher. I've installed a click application via `pkcon` on the terminal, and it's nowhere to be found. With the old dash, I could scroll down the application list to force a refresh, but this doesn't work with the new launcher.
Is there a way to trigger a refresh without killing unity8? Also, are the plans to add a click hook (or modifying an existing one) so that unity8 gets informed that an application has been installed?

**Comment by UniversalSuperBox** [comment]
I'm unable to confirm this. On a clean-installed image, I get icons when installing with `pkcon install-local`.

**Comment by UniversalSuperBox** [comment]
This was added in https://github.com/ubports/unity8/pull/174

**Comment by mardy** [comment]
Please give me one day to test it on a fresh image, it might be that this was due to me having installed a custom (and broken) package of ubuntu-app-launcher.

**Comment by mardy** [comment]
I tried on a fresh image, and everything works as expected. Sorry for the noise! :-)
