### ISSUE TITLE
app opened when tapping on notification in indicator is not on top

### ISSUE THREAD

**Issue by Fuseteam** [ubports/unity8#247]
tapping on an app notification changes the focussed app to a seemingly random app, but never the app

for example tapping on at a teleports notification while morph is open; switches to say the gallery app instead of teleports

the app it switches to appears random but it never swiches to the intended app

Sometimes it switches to the intended app but and immediately switches away

tests were on a E5 on the devel channel

**Comment by UniversalSuperBox** [comment]
This should be fixed by https://github.com/ubports/unity8/pull/249
