### ISSUE TITLE
Splash screen with gradients doesn't show the expected colours

### ISSUE THREAD

**Issue by mymike00** [ubports/unity8#26]
If in the `.desktop` file of an app I add
`X-Ubuntu-Splash-Color-Header=#f4a142
X-Ubuntu-Splash-Color-Footer=#e92c40`
for example I get an extra black line that I don't want
![immagine](https://user-images.githubusercontent.com/28359593/36618748-9a6f0dc2-18ec-11e8-90e9-6e12eebacad8.png)

**Comment by abhisaini** [comment]
well i am up for solving the issue...gimme a bit time

**Comment by mymike00** [comment]
Great! I noticed that the gradients work removing  `-Footer` idk why but it may could help you

**Comment by abhisaini** [comment]
well i just want to make a successfull commit on any repo which has greater than 100 stars...
There is some reward for that in my college...If u can suggest me one than I will be thankful to u

**Comment by Flohack74** [comment]
I do not think we got any repo with more than 100 stars lol.

**Comment by Flohack74** [comment]
Ah no, its this one wow :)

**Comment by NeoTheThird** [comment]
> Great! I noticed that the gradients work removing -Footer idk why but it may could help you

Is this really a bug then?

I think you should be able to set `X-Ubuntu-Splash-Color` additionally, that should override the black default

**Comment by sverzegnassi** [comment]
It isn’t a bug. Gradient in splash screen has three different breakpoints, at 0.0 0.83 and 1.0, as defined for the ‘MainView’ component in the Ubuntu UI Toolkit.

Docs at: https://docs.ubuntu.com/phone/en/platform/guides/splash-screens

I’m not sure if the document is currently available on docs.ubports.com - in case, we’d need to fix that

**Comment by NeoTheThird** [comment]
Doesn't seem like it's there. Pinging @UniversalSuperBox, what do you think, do we want to get that section in?

**Comment by mymike00** [comment]
Thanks @sverzegnassi, but I can't find the 3 breakpoints in the docs you sent...

**Comment by NeoTheThird** [comment]
@mymike00 `X-Ubuntu-Splash-Color`, `X-Ubuntu-Splash-Color-Header` and `X-Ubuntu-Splash-Color-Footer`.

**Comment by sverzegnassi** [comment]
@mymike00 Those breakpoints are part of the Ambiance style used by the Ubuntu UI Toolkit `MainView`component. That style is reused internally in Unity8 to create the splash screen.

References:
- http://bazaar.launchpad.net/~ubuntu-sdk-team/ubuntu-ui-toolkit/trunk/view/head:/src/imports/Components/Themes/Ambiance/1.3/MainViewStyle.qml
- https://github.com/ubports/unity8/blob/xenial/qml/Stage/Splash.qml

**Comment by mymike00** [comment]
@NeoTheThird I meant the number/position of each breakpoint.
Thanks @sverzegnassi
We could include that numbers in the api-docs in the future splash screen page !

**Comment by Flohack74** [comment]
So this can be closed?

**Comment by mymike00** [comment]
Yes
