### ISSUE TITLE
wrong  CODING.md link in the README.md

### ISSUE THREAD

**Issue by Aury88** [ubports/unity8#27]
the  `CODING.md`  link in the [README.md](https://github.com/ubports/unity8/blob/xenial/README.md) [take to a 404 page](https://github.com/ubports/unity8/blob/xenial/CODING.md). 
Probably that  is due to the `.md` extension in the link/filename that currently is not in the [real filename](https://github.com/ubports/unity8/blob/xenial/CODING).

I would make a PR myself but I don't know if the link in `README` is correct and the file extension is missing (does it need inline text symbols that define how to format the text?) or if the link is incorrect.

**Comment by NeoTheThird** [comment]
Changed it to coding for now to fix the link, once @mariogrip updates the build instructions (#15) we should reconsider the use of that file, since it's not customary on github.
