### ISSUE TITLE
Prepare user environment for GDK wayland support

### ISSUE THREAD

**Issue by AlanGriffiths** [ubports/unity8#29]
GDK will try several graphics backends in sequence (based on an environment variable).

It would be good to ensure this is set in a way that works as Mir supports transitions from gtk-mir to Wayland: GDK_BACKEND=wayland,mir,x11

Until Mir supports the necessary Wayland extensions this will fall back to gtk-mir. If/when gtk-mir is removed it will use X11.

**Comment by dobey** [comment]
I'm closing this, as we're always setting GDK_BACKEND=wayland in bionic with the newer Mir, which is working, and I've not seen any reports of issues with that suggesting we need to fall back to mir or x11 yet.
