### ISSUE TITLE
Translations not up to date in Weblate

### ISSUE THREAD

**Issue by cibersheep** [ubports/unity8#297]
I wanted to update the translation for the App Drawer Tutorial but the file is not updated in Weblate :)

**Comment by Flohack74** [comment]
Turns out I slipped on resetting the branch to the edge merge stuff. So now we have fully broken unity8 translations. I hope I can fix it quickly without loosing already made translatioons though this is not sure.

**Comment by Flohack74** [comment]
Fixed by #300 and #303
