### ISSUE TITLE
[Arale][Dev] No Shell after update

### ISSUE THREAD

**Issue by cibersheep** [ubports/unity8#309]
Probably is just me (I did some ubports-qa updates) but with the last update in dev channel I got no Shell.qml. I opened issue to remember to test this properly.

![imatge](https://user-images.githubusercontent.com/6640041/80364106-9c263900-8885-11ea-95b2-dae73a1c6811.png)

Workaround: You need adb access to device, comment line 559 from /usr/share/unity8/Shell.qml and reboot.

**Comment by daleclack** [comment]
I experienced the same error
![VirtualBox_ubuntu-unity_10_05_2020_18_59_46](https://user-images.githubusercontent.com/63892434/81498034-18dcfc80-92f5-11ea-827b-42391deac027.png)

**Comment by cibersheep** [comment]
I'm pretty sure I was messing with the files :) 
Installing other channel and back to dev made this not happen again for me.

@daleclack have you being messing with shell qml? Or installing things with `ubports-qa`?

**Comment by daleclack** [comment]
I installed lomiri on ubuntu server 16.04, and now the error has disappeared.

**Comment by cibersheep** [comment]
Thanks. I'll close this then. Ping me or open a new issue if you experience this again, could you?

**Comment by daleclack** [comment]
OK
