### ISSUE TITLE
WindowStateStorage: threading wrong / broken on newer Qt

### ISSUE THREAD

**Issue by z3ntu** [ubports/unity8#316]
From the [Qt documentation](https://doc.qt.io/qt-5/threads-modules.html):
> A connection can only be used from within the thread that created it. Moving connections between threads or creating queries from a different thread is not supported.

We're opening and initializing the database on the main thread:
https://github.com/ubports/unity8/blob/34f8f8881053a3065a4bced9551c192eaacfdda9/plugins/Utils/windowstatestorage.cpp#L36-L45

We're doing the actual queries using a thread pool

https://github.com/ubports/unity8/blob/34f8f8881053a3065a4bced9551c192eaacfdda9/plugins/Utils/windowstatestorage.cpp#L175

https://github.com/ubports/unity8/blob/34f8f8881053a3065a4bced9551c192eaacfdda9/plugins/Utils/windowstatestorage.cpp#L113-L118

This clearly falls into the behavior mentioned in the documentation that this is not supported. Furthermore with Qt 5.14 (and likely older versions) this doesn't work anymore.

```
PASS   : WindowStateStorageTest::initTestCase()
QDEBUG : WindowStateStorageTest::testSaveRestoreState() constructor thread: 0x7f09e5671d48
QDEBUG : WindowStateStorageTest::testSaveRestoreState() ("QSQLITE", "QMYSQL", "QMYSQL3", "QODBC", "QODBC3", "QPSQL", "QPSQL7", "QTDS", "QTDS7")
QDEBUG : WindowStateStorageTest::testSaveRestoreState() dbpath: "/home/pmos/.qttest/cache/unity8/"
QDEBUG : WindowStateStorageTest::testSaveRestoreState() saveValue thread: 0x7f09e5671d48
QDEBUG : WindowStateStorageTest::testSaveRestoreState() executeAsyncQuery thread: 0x7f09e0e0cb20
QWARN  : WindowStateStorageTest::testSaveRestoreState() QSqlDatabasePrivate::database: requested database does not belong to the calling thread.
QWARN  : WindowStateStorageTest::testSaveRestoreState() QSqlQuery::exec: database not open
QWARN  : WindowStateStorageTest::testSaveRestoreState() Error executing query "INSERT OR REPLACE INTO state (windowId, state) values ('testSaveRestoreState', '256');" Driver error: "Driver not loaded" Database error: "Driver not loaded"
FAIL!  : WindowStateStorageTest::testSaveRestoreState() Compared values are not the same
   Actual   (((storage->getState(QTest::currentTestFunction(), WindowStateStorage::WindowState::WindowStateNormal)))): WindowStateNormal
   Expected (state)                                                                                                  : WindowStateMaximizedTopLeft
   Loc: [/home/pmos/build/src/unity8-34f8f8881053a3065a4bced9551c192eaacfdda9/tests/plugins/Utils/WindowStateStorageTest.cpp(44)]
```

**Comment by UniversalSuperBox** [comment]
Fixed by https://github.com/ubports/unity8/pull/356
