### ISSUE TITLE
Drawer exhibits poor scrolling performance, especially with many apps.

### ISSUE THREAD

**Issue by Talkless** [ubports/unity8#342]
With OTA-12 we got new app list / drawer with transparent background, and with that I've noticed that scrolling it is no longer "sleek" - it looks like it stutters as if it where loading app icons synchronously.

Previously it "felt" as if icons where loaded asynchronously without much issue. Now it's kinda "painful" to watch...

I've waited for OTA-13 expecting it would be known and fixed, but the issue persists.

**Comment by UniversalSuperBox** [comment]
I believe this should be closed with https://github.com/ubports/unity8/issues/364

**Comment by Talkless** [comment]
> I believe this should be closed with #364

I disagree, still issue with OTA-18.
