### ISSUE TITLE
ListView does not return swiped item to original unswiped state with mouse

### ISSUE THREAD

**Issue by Danfro** [ubports/unity8#357]
When swiping an item in a ListView it stays at it moved position (left/right). The `swiped` property is set to `true`.
Once the list is scrolled up/down, the item gets moved back to it's zero position and `swiped` is set to `false`.

When using a mouse, the list item is not moved back to zero and `swiped` is not set to false. When the item moves out of view and comes back, it is back to its zero position, but `swiped` is still not set to `false`.

This problem came up while working on this [MR](https://gitlab.com/ubports/apps/teleports/-/merge_requests/373) for Teleports when trying to auto-disable fastscroll when an item is swiped. Because `swiped` is readonly, I currently see no way to force the item to it's "unswiped" state. Even moving it to zero position does not reset `swiped` state.

**Comment by lduboeuf** [comment]
Are you sure it is a Lomiri issue not in UI Toolkit ?

**Comment by Danfro** [comment]
Sight. Too many repos. Sure, it needs to go to UI toolkit. Thanks @lduboeuf .
