### ISSUE TITLE
Allow greeter rotation

### ISSUE THREAD

**Issue by capsia37** [ubports/unity8#419]
Allow the greeter to rotate and make it responsive so it will look good at any screen size.

**Comment by j2g2rp** [comment]
Rotation is working fine on M10FHD and on Volla x.
I would say that there is just one problem of consistency on M10FHD when it is horizontal:
Here is the greeting screen on M10 when horizontal before swiping:
![screenshot20220116_181732784](https://user-images.githubusercontent.com/28528967/149672069-b349e2f7-2334-4dbd-9d90-d82f680a9df2.png)
after swiping:
![screenshot20220116_181743321](https://user-images.githubusercontent.com/28528967/149672153-daf0b87e-a643-4af4-b07c-75f4e2a87399.png)
and this is when vertical before swiping:
![screenshot20220116_181756631](https://user-images.githubusercontent.com/28528967/149672160-eaba9f6e-bbbc-4347-93ad-d58e7ce9de08.png)
after swiping:
![screenshot20220116_181810912](https://user-images.githubusercontent.com/28528967/149672177-d2e0f664-bc60-4204-a7fe-272212e7f849.png)

On vollaphone seems consistent on horizontal:
![screenshot20220116_183827588](https://user-images.githubusercontent.com/28528967/149672207-79f94405-6fc6-422c-9bc3-df68a692ccb4.png)
![screenshot20220116_183833474](https://user-images.githubusercontent.com/28528967/149672214-d3280612-92e6-4dc7-9ef4-cae0b9105c26.png)

PS. I waited this feature for years, thank you! 😁😁😁

**Comment by capsia37** [comment]
> Rotation is working fine on M10FHD and on Volla x. I would say that there is just one problem of consistency on M10FHD when it is horizontal: Here is the greeting screen on M10 when horizontal before swiping.

Hello @j2g2rp and thank you for the feedback. I've originally wanted to move the infographics in tablet and desktop mode near the login prompt to allow showing and updating them while switching users in a multi-user setup. In the portrait mode the infographics wouldn't fit, but in landscape I've put it there. Since we are currently limited to only one user anyway, it would be more consistent to keep it always on the cover page :)

**Comment by cibersheep** [comment]
There is an small issue ^_^
https://github.com/ubports/unity8/issues/422

**Comment by c4pp4** [comment]
RC OTA22: 2022-W04 (devices: Mi A2 (display (1080 x 2160) and Xperia X (display 1080x1920))
Works. There is no issue like 422. But one thing I noticed. When in landscape orientation, keyboard on Xperia X fills 1/2 of display height and it's very comfortable to write on it. On the other hand the keyboard on Mi A2 fills cca 1/4 of display height and is very tiny, just like @j2g2rp Volla phone screenshot.
