### ISSUE TITLE
Greeter design - weird passcode input colors

### ISSUE THREAD

**Issue by c4pp4** [ubports/unity8#420]
Release: dev OTA-21 with applied #401

### Steps to reproduce
Set unlock device with passcode

### Expected behavior
When entering passcode, each circle is filled with white color.

### Actual behavior
When entering passcode, each circle is filled with white color except the last one. When the last number is entered, it looks like this:

![Greeter image](https://user-images.githubusercontent.com/18672800/145180769-dd1f3bf9-c279-4d87-a532-955cf4d18a4f.jpg)

**Comment by gurucubano** [comment]
The last correct digit should fill the last circle and than (after half second) should give access to the phone's desktop.

**Comment by maciek134** [comment]
Filling the last circle is alright, but let's not delay the unlock action just to see it a bit longer please.
