### ISSUE TITLE
Unnecessary prompts loading

### ISSUE THREAD

**Issue by lduboeuf** [ubports/unity8#428]
Today, if a user have a pinCode prompt, the code will load ButtonPrompt.qml, TextPrompt.qml and finally PinPrompt.qml.
https://github.com/ubports/unity8/blob/xenial/qml/Greeter/GreeterPrompt.qml#L110
Making unnecessary component loading and may lead to focus issue.

**Comment by lduboeuf** [comment]
Note to testers: There is no way to test explicitly, except check if no regression with pincode and passphrase login: first load,  logout/login etc...

**Comment by gbdomubpkm** [comment]
Hello.
It is (probably) not the good place so sorry in advance if it is the case as i don't know if there is some work about that :
Is it normal for the keyboard to be there before unlocking the Pin code? Seen on the Volla in RC.
![screenshot20220603_080617764](https://user-images.githubusercontent.com/50362604/171799244-6bd94c5d-2749-4242-ab90-1398cb21e2f4.png)

However, the keyboard no longer appears before unlocking if I make the screen black and then turn it back on (power key).

**Comment by lduboeuf** [comment]
humm, it should not, it happens every time ?
Can't reproduce here

**Comment by gbdomubpkm** [comment]
Yes every time on Volla.

**Comment by lduboeuf** [comment]
do you have Pincode after or passphrase prompt ?

**Comment by gbdomubpkm** [comment]
Hello @peat-psuwit . As i read somewhere you have a Volla, can you confirm this ? Thanks.

**Comment by gbdomubpkm** [comment]
@lduboeuf I just checked and indeed, if I program an unlocking of the phone by passphrase instead of a pincode, the keyboard does not appear for the PIN SIM.

**Comment by lduboeuf** [comment]
humm, weird, do you confirm the issue on devel ?
But before can you provide the unity8 logs ?

**Comment by gbdomubpkm** [comment]
I am on today RC and will stay/must stay on RC.

But, strange and good thing. I reinstalled a Volla unlock by pincode and the problem disappeared. I checked by doing four restarts of the Volla.
Before today, i always unlocked the Volla by pincode.
It is the first time i installed a passphrase.
And it seems that, when i came back to pincode, the keyboard problem is solved.

**Comment by Flohack74** [comment]
The keyboard appearing during SIM PIN entry is a different issue: https://github.com/ubports/ubuntu-touch/issues/1404 open since 2020

**Comment by Flohack74** [comment]
@gbdomubpkm I have another interesting issue, when I have fingerprint active and I want to change back to passphrase e.g. or PIN I can register a new passphrase or PIN but it will stay on fingerprint. Only if I go into that option a second time it will change the method finally.

**Comment by lduboeuf** [comment]
> @gbdomubpkm I have another interesting issue, when I have fingerprint active and I want to change back to passphrase e.g. or PIN I can register a new passphrase or PIN but it will stay on fingerprint. Only if I go into that option a second time it will change the method finally.

humm is this a regression ? I doubt that PR is the cause, but who knows...

**Comment by Flohack74** [comment]
No its not that PR I think. Maybe was always like that
