### ISSUE TITLE
Launcher and Drawer automatically hides after using mouse cursor to open them

### ISSUE THREAD

**Issue by kugiigi** [ubports/unity8#431]
### Steps to Reproduce
1. Connect a mouse
2. Open at least one app
3. Push the mouse to the left edge until the Drawer opens

### Expected Result
The drawer opens until the user closes it via swipe or pressing the BFB.

### Actual Results
Launcher and drawer automatically closes regardless of how they were opened. This will persist until Lomiri is restarted.

### Additional Information
This is supposed to be fixed but I don't think it was ever fixed though it was tagged as fixed and it was Michael Zanetti so I'm cinfused,
I'd doubt myself before doubting his work :smile: 
Original bug: https://bugs.launchpad.net/ubuntu/+source/unity8/+bug/1657045

In my understanding, the autohiding is supposed to only happen when the launcher is opened via pushing the mouse to the edge. It will automatically close once the mouse exists the launcher area.

**Comment by fredldotme** [comment]
Bugfix tracking here: https://github.com/ubports/unity8/pull/432
