### ISSUE TITLE
[idea] Make an option for dock not to disappear after closing apps

### ISSUE THREAD

**Issue by konradybcio** [ubports/unity8#47]
It's quite irritating that when I use "quit" on an app on the dock (I don't like the swipe-from-right-to-left app switcher) I have to summon it every time

**Comment by dobey** [comment]
Can you clarify please? This is on phone, tablet, or PC? Thanks.

**Comment by UniversalSuperBox** [comment]
Without more information, we won't be able to investigate and solve this issue.

@konradybcio, please feel free to open a new issue with more information.
