### ISSUE TITLE
Why Unity continues making top position of the taskbar a default option?

### ISSUE THREAD

**Issue by BoQsc** [ubports/unity8#49]
![be pavadinimo](https://user-images.githubusercontent.com/21064622/43003636-c9296704-8c35-11e8-880b-63f25232c829.png)
I have huge problem with my laptop having this at the top, 
as the monitor level is very low compared to the eye level. 

Also after opening an application, the application's title bar does not merge with the taskbar and only takes even more space at the top of the monitor.

Can I suggest, making the taskbar of unity to be always at the bottom of the monitor after installation?

**Comment by UniversalSuperBox** [comment]
Unity's design has always required the panel be at the top of the screen. This is so it could house the global menu and window controls for a maximized application.

> after opening an application, the application's title bar does not merge with the taskbar and only takes even more space at the top of the monitor.

This is solved by adding global menus back to Unity8, which is a planned but not currently in progress feature. Rest assured, we are aware of the problem (and it's really annoying!).

We will not be changing this fundamental design feature of Unity8.
