### ISSUE TITLE
Using LightDM, after log out from Unity8, can't log into Unity7 (but can log into GNOME)

### ISSUE THREAD

**Issue by GizmoChicken** [ubports/unity8#50]
As reported [elsewhere](https://github.com/ubports/unity8-desktop-install-tools/issues/35), after first installing Unity8 from the UBports repo, and then installing Mir 0.32.1 from [ppa:mir-team/release](https://launchpad.net/%7Emir-team/+archive/ubuntu/release), I can now log into Unity8 using LightDM.  Also, if I log into Unity7 first, and then log out of Unity7, I can log into Unity8.

However, _upon log out of Unity8_, I am unable log into Unity7 using LightDM. Rather, when attempting to do so, I enter a login loop.  The first attempt to log into Unity7 (after log out form Unity8) generally returns me to the login prompt within a few seconds, at most.  But the second (and subsequent) attempt hangs for about one or two _minutes_ before returning me to the login prompt.

Once returned to the login prompt, I am able to log into GNOME using LightDM. And in fact, I can switch between Unity8 and GNOME without trouble using LightDM.  Also, I can switch between GNOME and Unity7 without trouble using LightDM. But upon log out of Unity8, _invariably_, I can't log into Unity7 using LightDM. Very strange.

To reiterate, the above occurs when using LightDM.  Consistent with what has been reported [elsewhere](https://github.com/ubports/unity8-desktop-install-tools/issues/36), I am unable to log into Unity8 using GDM.

System:
Processor: Intel Core i5-6200U
Graphics: Intel HD Graphics 520
Distro: Ubuntu 18.04 LTS (64-bit) onto which Unity7 (ubuntu-unity-desktop from the Universe repo), Unity8 (from the UBports repo), and Mir 0.32.1 (from ppa:mir-team/release) are installed

EDIT:  As an aside, at present, I don't really have much need for switching between Unity8 and other DEs. So from my perspective, fixing the bug described above isn't urgent. But if exploring this bug helps sort out undiscovered issues with the Unity8/Mir interaction, given appropriate guidance, I'd be happy to help provide logs and/or other information.

**Comment by UniversalSuperBox** [comment]
I believe this issue was filed regarding a unity8 desktop installer. We are not currently able to offer support for this... We may release more proper desktop installers with our transition of Ubuntu Touch to Ubuntu 20.04, or another distribution may provide proper images with Lomiri.

Either way, I believe this issue should be closed since this revision of the project is essentially dropped. Lomiri will still come back to the desktop, but not using unity8-desktop-install-tools.
