### ISSUE TITLE
The "indicator-keyboard" package from the UBports repo has unresolvable dependencies

### ISSUE THREAD

**Issue by GizmoChicken** [ubports/unity8#52]
On my system (Ubuntu 18.04 LTS onto which the [ubuntu-unity-desktop](https://packages.ubuntu.com/bionic/ubuntu-unity-desktop) meta-package has been installed from the Universe repo), the Unity8 installer attempts to upgrade [indicator-keyboard/bionic](https://packages.ubuntu.com/bionic/indicator-keyboard) to a newer version found in the UBports repo. However, at least on my system, indicator-keyboard/bionic from the UBports repo has unresolvable dependencies, and so the Unity8 installer fails to upgrade this one package. 

Info from terminal:

> $ sudo apt list --upgradable
> Listing... Done
> indicator-keyboard/bionic 0.0.1+ubports1+0~20180219162249.1~1.gbp660b9a amd64 [upgradable from: 0.0.0+18.04.20180216-0ubuntu1]
> N: There is 1 additional version. Please use the '-a' switch to see it

Info from Synaptic:

>The following packages have unresolvable dependencies.  Make sure that all required respositories are added and enabled in the preferences.
> 
> indicator-keyboard:
>  Depends: libgnome-desktop-3-12 (>=3.17.92) but it is not installable

**Comment by dobey** [comment]
This is fixed now.
