### ISSUE TITLE
Normal Desktop with symbols

### ISSUE THREAD

**Issue by cknost** [ubports/unity8#55]
Hello,
i wish a normal Desktop like on unity7 too, like on unity7, gnome, lxde...

**Comment by dobey** [comment]
I'm not sure what you're asking here. You can still use unity7 in Ubuntu 18.04 simply by installing it, if that's what you wish for. Unity8 is not and will not be the same as unity7, but we are working to make it usable as a daily environment on PCs as well. I'm going to close this. If you feel this should remain open, please clarify what you are asking for. Thanks.
