### ISSUE TITLE
Erro ao instalar sobre Ubuntu 32 bits

### ISSUE THREAD

**Issue by robertoduwe** [ubports/unity8#59]
Criei uma VM de 32 bits no VirtualBox e instalei o Ubuntu Minimal 18.041 32 bits.
Depois instalei o pacote ubuntu-desktop.
Assim consegui obter o Ubuntu 18.04.1 de 32 bits.

Após isto, tentei instalar o unity 8 através do script https://raw.githubusercontent.com/ubports/unity8-desktop-install-tools/master/install.sh.

Neste processo recebo o seguinte erro:
Alguns pacotes não puderam ser instalados. Isto pode significar que
você solicitou uma situação impossível ou, se você está usando a
distribuição instável, que alguns pacotes requeridos não foram
criados ainda ou foram retirados da "Incoming".
A informação a seguir pode ajudar a resolver a situação:

Os pacotes a seguir têm dependências desencontradas:
 unity8-desktop-session : Depende: policykit-unity8 mas não é instalável
                          Depende: qtmir-desktop mas não é instalável
                          Depende: unity8 mas não é instalável
                          Recomenda: indicator-transfer mas não é instalável
                          Recomenda: qtubuntu-print mas não é instalável
                          Recomenda: ubuntu-terminal-app mas não é instalável
                          Recomenda: unity-scope-mediascanner2 mas não é instalável
                          Recomenda: webbrowser-app mas não é instalável
E: Impossível corrigir problemas, você manteve (hold) pacotes quebrados.

Gostaria de instalar o unity 8 em um notebook de 32 bits que tenho para teste.

**Comment by GizmoChicken** [comment]
> I would like to install Unity 8 on a 32-bit notebook I have to test. 

I may be wrong, but I'm under the impression that you won't be able to install Unity8 onto a 32-bit version of Ubuntu 18.04 within the foreseeable future.

Please keep in mind that Unity8 is still a _very early development preview_.  Even if you could install Unity8 onto a 32-bit version of Ubuntu 18.04, in its current form, it wouldn't yet be very useful to you.  It is here mostly for those of us who want to follow its development.

**Comment by robertoduwe** [comment]
Ok.
Mesmo assim gostaria de testar.
Poderiam resolver estas dependências para que a instalação funcione?
Agradeço.

**Comment by UniversalSuperBox** [comment]
I believe this issue was filed regarding a unity8 desktop installer. We are not currently able to offer support for this, and much has changed in the three years between the report and now... We may release more proper desktop installers with our transition of Ubuntu Touch to Ubuntu 20.04, or another distribution may provide proper images with Lomiri.

Either way, I believe this issue should be closed due to its age.
