### ISSUE TITLE
Plugin cannot be loaded for module "Unity.Screens"

### ISSUE THREAD

**Issue by PatrickMitchellUI** [ubports/unity8#85]
> `[2018-11-12:11:08:34.576] QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-xstma'
[2018-11-12:11:08:34.583] failed to get the current screen resources
[2018-11-12:11:08:34.640] Mode argument was not provided or was set to an illegal value. Using default value of --mode= "full-greeter"
WARNING: Application calling GLX 1.3 function "glXCreatePbuffer" when GLX 1.3 is not supported!  This is an application bug!
[2018-11-12:11:08:34.769] file:///usr/share/unity8//OrientedShell.qml:21:1: plugin cannot be loaded for module "Unity.Screens": Cannot load library /usr/lib/x86_64-linux-gnu/qt5/qml/Unity/Screens/libunityscreensplugin.so: (libqpa-mirserver.so: cannot open shared object file: No such file or directory)
     import Unity.Screens 0.1
     ^
[2018-11-12:11:08:34.889] QXcbConnection: XCB error: 170 (Unknown), sequence: 170, resource id: 90, major code: 146 (Unknown), minor code: 20`

SYSINFO READOUT
`System information report, generated by Sysinfo: 11/12/2018 11:14:33
http://sourceforge.net/projects/gsysinfo

SYSTEM INFORMATION
        Running Ubuntu Linux, the Ubuntu 18.04 (bionic) release.
        GNOME: 3.28.2 (Ubuntu)
        Kernel version: 4.4.0-17763-Microsoft (unknown)
        GCC: no gcc detected
        Xorg: unknown
        Hostname: LAPPY
        Uptime: 0 days 1 h 14 min

CPU INFORMATION
        GenuineIntel, Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz
        Number of CPUs: 4
        CPU clock currently at 2712.000 MHz with 256 KB cache
        Numbering: family(6) model(142) stepping(9)
        Bogomips: 5424.00
        Flags: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm pni$`

**Comment by dobey** [comment]
You are trying to run Unity8 inside the WSL on Windows 10?

**Comment by PatrickMitchellUI** [comment]
Yes :) but i have no clue what libunityscreenplugin is

**Comment by dobey** [comment]
OK. WSL is not supported for running unity8 on, and I'm pretty sure you can't run a Mir/Wayland compositor under WSL either. So I'm going to close this bug.

Why are you trying to run the Unity8 shell under WSL?

The Unity.Screens plug-in is a QML plug-in provided by unity8. It's failing to load because you seem to not have the `qtmir-desktop` package installed (though even if you do install it, it almost certainly will not work).

**Comment by vanyasem** [comment]
lol i like that guy. nice spirit.
